@startuml

class Letter {
    - value: int
    + getValue()
}

class Collection {
    + getValueByKey(String str): String
}

class Client {
}

Letter --* Collection
Client --> Collection
Letter --|> Collection

class Agregation {
}

class Iterator {
    + next(): Object
    + hasNext(): bool
}

Agregation -- Iterator

'FlyWeight Patter

@enduml
